version: "3"
name: sonarqube
services:
  # SONARQUBE SERVICES ################################################################

  sonarqube:
    image: sonarqube:lts-community
    hostname: sonarqube
    container_name: instance
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  db:
    image: postgres:13
    hostname: postgresql
    container_name: database
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
# END SONARQUBE SERVICES ############################################################

volumes:
  # SONARQUBE VOLUMES ################################################################
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
# END SONARQUBE VOLUMES ##########################################################

networks:
  default:
    name: "sonarqube"