name: Deploy LOCAL Playground to GitHub Pages

on:
  #push:
    #    branches:
    #        - gh-pages
    
    workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install --prefer-offline --legacy-peer-deps

      - name: Build App
        run: npm run build:gh-pages:playground

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_branch: gh-pages
          publish_dir: ./dist/playground
          destination_dir: playground
